# Bias 
     it is the simplifying assumptions made by the model to make the target function easy
## Variance
        it is the amount that the estimate of the target function will change given different training data

# Overfitting
       Whenever the model is having a low bias and high variance
## Underfitting
         Whenever the model is having a high bias and loe variance

## Ridge regression
        Adds "Squared magnitude" of coeefient as penaliity to the loss function
# Losso Regression
        Adds "absolute value of magnitude" of coefficient as penality team to the loss function
            

# How to prevent overfitting and underfitting
    1.Cross validation- it is powerful preventative measure aganist overfitting
    2.train with more data
    3.remove features
    4.Early stopping
    5.Reglarzation
    6.Ensembling

In [34]:
# import required packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
m = 100
x = np.random.rand(m,1)
y = 0.5*x**2+x+2+np.random.randn(m,1)  ##ax^2+bx+c


In [36]:
print(x)

[[0.93549933]
 [0.5592542 ]
 [0.16500571]
 [0.51373712]
 [0.32478904]
 [0.12137973]
 [0.06405281]
 [0.79302125]
 [0.44751523]
 [0.61980126]
 [0.44388277]
 [0.03668088]
 [0.41926619]
 [0.34742953]
 [0.20564554]
 [0.67271938]
 [0.21706242]
 [0.7495068 ]
 [0.22403975]
 [0.29719784]
 [0.96490562]
 [0.5126391 ]
 [0.71395057]
 [0.2826448 ]
 [0.70386837]
 [0.00387555]
 [0.75138962]
 [0.28357895]
 [0.23105413]
 [0.45902742]
 [0.975222  ]
 [0.3362159 ]
 [0.93629339]
 [0.03880495]
 [0.6720465 ]
 [0.7931414 ]
 [0.07107869]
 [0.98243938]
 [0.03619657]
 [0.36931479]
 [0.57336239]
 [0.33995216]
 [0.82551593]
 [0.69659373]
 [0.77670563]
 [0.22181159]
 [0.59464451]
 [0.55379891]
 [0.63954413]
 [0.17109638]
 [0.14692431]
 [0.6949162 ]
 [0.04240189]
 [0.6272002 ]
 [0.15981064]
 [0.22375196]
 [0.97088177]
 [0.77526171]
 [0.67847326]
 [0.98542935]
 [0.72998735]
 [0.85848707]
 [0.08638359]
 [0.02088551]
 [0.84679526]
 [0.03212539]
 [0.72072772]
 [0.10828399]
 [0.34245708]
 [0.75240954]
 [0.38587108]
 [0.67

In [37]:
print(x,"x values")
print(y,"y values")
print(m)

[[0.93549933]
 [0.5592542 ]
 [0.16500571]
 [0.51373712]
 [0.32478904]
 [0.12137973]
 [0.06405281]
 [0.79302125]
 [0.44751523]
 [0.61980126]
 [0.44388277]
 [0.03668088]
 [0.41926619]
 [0.34742953]
 [0.20564554]
 [0.67271938]
 [0.21706242]
 [0.7495068 ]
 [0.22403975]
 [0.29719784]
 [0.96490562]
 [0.5126391 ]
 [0.71395057]
 [0.2826448 ]
 [0.70386837]
 [0.00387555]
 [0.75138962]
 [0.28357895]
 [0.23105413]
 [0.45902742]
 [0.975222  ]
 [0.3362159 ]
 [0.93629339]
 [0.03880495]
 [0.6720465 ]
 [0.7931414 ]
 [0.07107869]
 [0.98243938]
 [0.03619657]
 [0.36931479]
 [0.57336239]
 [0.33995216]
 [0.82551593]
 [0.69659373]
 [0.77670563]
 [0.22181159]
 [0.59464451]
 [0.55379891]
 [0.63954413]
 [0.17109638]
 [0.14692431]
 [0.6949162 ]
 [0.04240189]
 [0.6272002 ]
 [0.15981064]
 [0.22375196]
 [0.97088177]
 [0.77526171]
 [0.67847326]
 [0.98542935]
 [0.72998735]
 [0.85848707]
 [0.08638359]
 [0.02088551]
 [0.84679526]
 [0.03212539]
 [0.72072772]
 [0.10828399]
 [0.34245708]
 [0.75240954]
 [0.38587108]
 [0.67

In [38]:
x.shape

(100, 1)

In [39]:
y.shape

(100, 1)

In [40]:
from sklearn.linear_model import Ridge
rd = Ridge()

In [41]:
x[1]

array([0.5592542])

In [42]:
y[1]

array([3.6399259])

In [43]:
np.ndim(x)

2

In [44]:
#fit data to model
rd.fit(x,y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [45]:
rd.predict(x[[1]])

array([[2.70155865]])

In [46]:
from sklearn.datasets import load_boston

In [47]:
boston = load_boston()

In [48]:
print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [49]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [50]:
df = pd.DataFrame(boston.data,columns=boston.feature_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [51]:
df.shape

(506, 13)

In [52]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

In [53]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [54]:
df['Landprice'] = boston.target

In [55]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Landprice  
0     15.3  396.90   4.98       24.0  
1     17.8  396.90   9.14       21.6  
2     17.8  392.83   4.03       34.7  
3     18.7  394.63   2.94       33.4  
4     18.7  396.90   5.33       36.2

In [56]:
df.isnull().sum()

CRIM         0
ZN           0
INDUS        0
CHAS         0
NOX          0
RM           0
AGE          0
DIS          0
RAD          0
TAX          0
PTRATIO      0
B            0
LSTAT        0
Landprice    0
dtype: int64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM         506 non-null float64
ZN           506 non-null float64
INDUS        506 non-null float64
CHAS         506 non-null float64
NOX          506 non-null float64
RM           506 non-null float64
AGE          506 non-null float64
DIS          506 non-null float64
RAD          506 non-null float64
TAX          506 non-null float64
PTRATIO      506 non-null float64
B            506 non-null float64
LSTAT        506 non-null float64
Landprice    506 non-null float64
dtypes: float64(14)
memory usage: 55.4 KB


In [58]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT   Landprice  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [59]:
# seperate the input and target features
x = df.iloc[:,0:-1]
x.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [60]:
y = df['Landprice']
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
5      28.7
6      22.9
7      27.1
8      16.5
9      18.9
10     15.0
11     18.9
12     21.7
13     20.4
14     18.2
15     19.9
16     23.1
17     17.5
18     20.2
19     18.2
20     13.6
21     19.6
22     15.2
23     14.5
24     15.6
25     13.9
26     16.6
27     14.8
28     18.4
29     21.0
       ... 
476    16.7
477    12.0
478    14.6
479    21.4
480    23.0
481    23.7
482    25.0
483    21.8
484    20.6
485    21.2
486    19.1
487    20.6
488    15.2
489     7.0
490     8.1
491    13.6
492    20.1
493    21.8
494    24.5
495    23.1
496    19.7
497    18.3
498    21.2
499    17.5
500    16.8
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Landprice, Length: 506, dtype: float64

In [61]:
# apply the model
from sklearn.linear_model import LinearRegression
lin_alg = LinearRegression()

In [62]:
# Train the model by using fit
lin_alg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [63]:
df.shape

(506, 14)

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.75,random_state = 2)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [65]:
print("LR Train Score:",lin_alg.score(x_train,y_train))

LR Train Score: 0.732096496098996


In [66]:
print("LR Test Score:",lin_alg.score(x_test,y_test))

LR Test Score: 0.7637142214450796


# Disadvantages
        If not of independent varible increses,